### ISSUE TITLE
Failed to build for Runelite Plugin-hub

### ISSUE THREAD

**Issue by unkindlykiller** [Equinox-/runelite-influxdb#14]
disappear from the runelite client after i had just got it all setup :/ looked around for why found it failed to build...i sadly dunno how to update it

Cloning into '/tmp/pluginhub-package4744414850761423079/influxdb-stats/repo'...
HEAD is now at 09804bb Wrap 100 character long line Fixes #13
download: 810ms
Dependency verification is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':runelitePluginHubPackage'.
> Dependency verification failed for configuration ':runtimeClasspath'
  7 artifacts failed verification:
    - guava-20.0.jar (com.google.guava:guava:20.0) from repository MavenRepo
    - guava-20.0.pom (com.google.guava:guava:20.0) from repository MavenRepo
    - guava-parent-20.0.pom (com.google.guava:guava-parent:20.0) from repository MavenRepo
    - okhttp-3.5.0.jar (com.squareup.okhttp3:okhttp:3.5.0) from repository MavenRepo
    - okio-1.11.0.jar (com.squareup.okio:okio:1.11.0) from repository MavenRepo
    - okio-1.11.0.pom (com.squareup.okio:okio:1.11.0) from repository MavenRepo
    - okio-parent-1.11.0.pom (com.squareup.okio:okio-parent:1.11.0) from repository MavenRepo
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.6.1/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  Open this report for more details: file:///tmp/pluginhub-package4744414850761423079/influxdb-stats/repo/build/reports/dependency-verification/at-1614786497150/dependency-verification-report.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 38s
build: 38637ms
package failed
net.runelite.pluginhub.packager.PluginBuildException: influxdb-stats: build failed
	at net.runelite.pluginhub.packager.PluginBuildException.of(PluginBuildException.java:54)
	at net.runelite.pluginhub.packager.Plugin.build(Plugin.java:434)
	at net.runelite.pluginhub.packager.Packager.buildPlugin(Packager.java:157)
	at net.runelite.pluginhub.packager.Packager.lambda$buildPlugins$0(Packager.java:109)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.gradle.tooling.BuildException: Could not execute build using connection to Gradle installation '/home/runner/.gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1'.
	...
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	...
	... 1 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Could not determine the dependencies of task ':runelitePluginHubPackage'.
	...
Caused by: org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':runelitePluginHubPackage'.
	...
	... 72 more
Caused by: org.gradle.api.InvalidUserDataException: Dependency verification failed for configuration ':runtimeClasspath'
7 artifacts failed verification:
  - guava-20.0.jar (com.google.guava:guava:20.0) from repository MavenRepo
  - guava-20.0.pom (com.google.guava:guava:20.0) from repository MavenRepo
  - guava-parent-20.0.pom (com.google.guava:guava-parent:20.0) from repository MavenRepo
  - okhttp-3.5.0.jar (com.squareup.okhttp3:okhttp:3.5.0) from repository MavenRepo
  - okio-1.11.0.jar (com.squareup.okio:okio:1.11.0) from repository MavenRepo
  - okio-1.11.0.pom (com.squareup.okio:okio:1.11.0) from repository MavenRepo
  - okio-parent-1.11.0.pom (com.squareup.okio:okio-parent:1.11.0) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.6.1/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///tmp/pluginhub-package4744414850761423079/influxdb-stats/repo/build/reports/dependency-verification/at-1614786497150/dependency-verification-report.html
	...
	at jdk.internal.reflect.GeneratedMethodAccessor112.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	...
	at com.github.jengelman.gradle.plugins.shadow.internal.AbstractDependencyFilter.resolve(AbstractDependencyFilter.groovy:32)
	at jdk.internal.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.github.jengelman.gradle.plugins.shadow.internal.AbstractDependencyFilter$_resolve_closure2.doCall(AbstractDependencyFilter.groovy:39)
	at jdk.internal.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.github.jengelman.gradle.plugins.shadow.internal.AbstractDependencyFilter.resolve(AbstractDependencyFilter.groovy:38)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar$1.call(ShadowJar.java:50)
	at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar$1.call(ShadowJar.java:46)
	...
	... 108 more

influxdb-stats: build failed

**Comment by Equinox-** [comment]
I'll get this fixed in the next couple days.

**Comment by Equinox-** [comment]
Fixed by https://github.com/runelite/plugin-hub/pull/1184
