### ISSUE TITLE
Trouble connecting to Influx

### ISSUE THREAD

**Issue by hjdarnel** [Equinox-/runelite-influxdb#3]
Hey, I recently set up an instance of InfluxDB on my local network. I'm trying to connect but Influx isn't receiving any data. Do you have an example of a configuration that works? For example, I'm not sure if server url requires http:// or not, among other.

My database is able to be pinged with a `curl my.local.ip/ping` and it responds accurately, so I'm not sure how my runelite configuration could be messed up (server url `http://my.local.ip` password correct username correct database correct)

Thanks in advance! I think an anonymized version of your configuration would be helpful for the README.

**Comment by Equinox-** [comment]
You should check in `~/.runelite/logs` to see if you can figure out the error message.
The server URL should include http or https (depending on how you're hosting).

For example, my config has `https://influxdb.my.host` for the server URL.  If you have it on a non-default-for-the-protocol port then you'll need to make sure you set that with `https://influxdb.my.host:8443`.

**Comment by Equinox-** [comment]
I've identified the following bug when running on an official build of runelite:
```
java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:178)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:123)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:187)
	at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:48)
	at net.machpi.runelite.influxdb.write.InfluxWriter.getInflux(InfluxWriter.java:60)
	at net.machpi.runelite.influxdb.write.InfluxWriter.access$000(InfluxWriter.java:20)
	at net.machpi.runelite.influxdb.write.InfluxWriter$ThrottledWriter.flush(InfluxWriter.java:152)
	at net.machpi.runelite.influxdb.write.InfluxWriter$Writer.flush(InfluxWriter.java:111)
```

I'll work on fixing it.

**Comment by Equinox-** [comment]
Fixed by https://github.com/Equinox-/runelite-influxdb/commit/532aabc6ff171d2e75861981b02cdfd7d0c3eefa
Will verify once https://github.com/runelite/plugin-hub/pull/316 goes through

**Comment by hjdarnel** [comment]
Thanks! I can verify that this is working now. cheers!
