### ISSUE TITLE
Not connecting to InfluxDB

### ISSUE THREAD

**Issue by Zumzod** [Equinox-/runelite-influxdb#7]
Love the idea of the plugin but I just cant get it to connect to my influxDB.
Using InfluxDB with Chronograf/Grafana.

As database I created a new one called rs and RSDB
Created a user and I also tried with others that I use for other connections but it wont work.
As ServerURL i put: http://local-ip:8086
Server Username: The user I created/old ones
Server Password: The Password for the account I created.

```
2020-05-29 15:40:40 [pool-5-thread-1] ERROR n.m.runelite.influxdb.InfluxDbPlugin - Failed to write to influxDB 29 times
java.lang.NullPointerException: null
	at org.influxdb.impl.InfluxDBImpl.parseHostAddress(InfluxDBImpl.java:89)
	at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:73)
	at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:47)
	at net.machpi.runelite.influxdb.write.InfluxWriter.getInflux(InfluxWriter.java:66)
	at net.machpi.runelite.influxdb.write.InfluxWriter.flush(InfluxWriter.java:91)
	at net.machpi.runelite.influxdb.InfluxDbPlugin.flush(InfluxDbPlugin.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Edit:
I already have Telegraf running on this computer that sends data to InfluxDB so the connection should be fine. Also tried to use the same account but it wont work.

**Comment by Zumzod** [comment]
After 3 restarts of RuneLite it started working so I'll close this for now.
